#For creating the Kubernetes Deployment in the Minikube cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: babsgenius2001/react-frontend
        resources:
          limits:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
#For creating the Kubernetes Service in the Minikube cluster
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000